---
- hosts: localhost

  remote_user: root
  become: yes
  become_method: sudo

  pre_tasks:
  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-dev)"
    register: output
    changed_when:
    - output.stdout != ""
    - output.stdout != "\r\n"
    become: true

  - name: Gather facts
    setup:

  roles:
    - install
    - ssl
