---
- name: Restart nginx
  systemd:
    name: nginx
    state: restarted

- name: Restart dnsmasq
  systemd:
    name: dnsmasq
    state: restarted

- name: Restart uwsgi
  systemd:
    name: uwsgi
    state: restarted

- name: Enable nginx
  systemd:
    name: nginx
    enabled: yes
